[package]
name = "zerant-zcash"
version = "0.1.0"
edition = "2024"

[dependencies]
zerant-core = { path = "../zerant-core" }
zerant-credential = { path = "../zerant-credential" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
rusqlite = { version = "0.38", features = ["bundled"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json"] }
