[package]
name = "zerant-zcash"
version = "0.1.0"
edition = "2024"

[dependencies]
zerant-core = { path = "../zerant-core" }
zerant-credential = { path = "../zerant-credential" }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
rusqlite = { version = "0.38", features = ["bundled"] }
reqwest = { version = "0.13", default-features = false, features = ["blocking", "json"] }
zip321 = "=0.10.0-pre.0"
zcash_address = "=0.14.0-pre.0"
zcash_protocol = { version = "=0.11.0-pre.0", features = ["std"] }
zcash_client_backend = { version = "=0.24.0", default-features = false, features = ["lightwalletd-tonic", "lightwalletd-tonic-transport", "lightwalletd-tonic-tls-webpki-roots"] }
tokio = { version = "1", features = ["time"] }
url = { workspace = true }
